services:
  backend:
    image: ghcr.io/7artix/artilens-backend:latest
    container_name: artilens-backend
    restart: always
    volumes:
      - ${DATA_PATH:-./data}:/app/data
    environment:
      - PORT=3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: ghcr.io/7artix/artilens-frontend:latest
    container_name: artilens-frontend
    restart: always
    ports:
      - "${APP_PORT:-5555}:80"
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --label-enable